#syntax=docker/dockerfile:1.7
# Node 22: avoids "controller[kState].transformAlgorithm is not a function" when cache handler handles streams under load
FROM node:22-alpine AS builder

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# Layer caching: deps first so code-only changes don't re-run npm ci
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci --legacy-peer-deps

COPY . .

ARG NEXT_PUBLIC_API_BASE_URL=""
ARG NEXT_PUBLIC_IMAGE_BASE_URL=""
ARG NEXT_PUBLIC_STRAPI_TOKEN=""
ARG NEXT_PUBLIC_SITE_URL=""
ARG NEXT_PUBLIC_MATOMO_URL=""
ARG NEXT_PUBLIC_MATOMO_SITE_ID=""
ARG NEXT_PUBLIC_SENTRY_DSN=""
ARG STRAPI_BUILD_TIME_URL=""
ARG STRAPI_INTERNAL_URL=""
ARG FRONTEND_REDIS_URL=""
ARG GITHUB_SHA=""

ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_IMAGE_BASE_URL=${NEXT_PUBLIC_IMAGE_BASE_URL}
ENV NEXT_PUBLIC_STRAPI_TOKEN=${NEXT_PUBLIC_STRAPI_TOKEN}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_MATOMO_URL=${NEXT_PUBLIC_MATOMO_URL}
ENV NEXT_PUBLIC_MATOMO_SITE_ID=${NEXT_PUBLIC_MATOMO_SITE_ID}
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ENV STRAPI_BUILD_TIME_URL=${STRAPI_BUILD_TIME_URL}
ENV STRAPI_INTERNAL_URL=${STRAPI_INTERNAL_URL}
ENV FRONTEND_REDIS_URL=${FRONTEND_REDIS_URL}
ENV GITHUB_SHA=${GITHUB_SHA}

RUN NODE_ENV=production npm run build

FROM node:22-alpine AS runner
WORKDIR /app

# Runtime env: STRAPI_INTERNAL_URL, FRONTEND_REDIS_URL (STRAPI_BUILD_TIME_URL is build-only).
ARG STRAPI_INTERNAL_URL=""
ARG FRONTEND_REDIS_URL=""

ENV NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production \
    STRAPI_INTERNAL_URL=${STRAPI_INTERNAL_URL} \
    FRONTEND_REDIS_URL=${FRONTEND_REDIS_URL}

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
