export default () => ({
  "rest-cache": {
    config: {
      provider: {
        name: "memory",
        getTimeout: 100,
        options: {
          max: 100000,
          maxAge: 24 * 60 * 60 * 1000,
        },
      },
      strategy: {
        contentTypes: [
          "api::cart.cart",
          "api::cart-item.cart-item",
          "api::contract.contract",
          "api::contract-transaction.contract-transaction",
          "api::discount.discount",
          "api::footer.footer",
          "api::general-discount.general-discount",

          "api::local-user-address.local-user-address",
          "api::local-user-info.local-user-info",
          "api::local-user-permission.local-user-permission",
          "api::local-user-role.local-user-role",
          "api::local-user-wallet.local-user-wallet",
          "api::local-user-wallet-transaction.local-user-wallet-transaction",
          "api::navigation.navigation",
          "api::order.order",
          "api::order-item.order-item",
          "api::payment-gateway.payment-gateway",
          "api::product.product",
          "api::product-category.product-category",
          "api::product-category-content.product-category-content",
          "api::product-faq.product-faq",
          "api::product-like.product-like",
          "api::product-review.product-review",
          "api::product-review-like.product-review-like",
          "api::product-review-reply.product-review-reply",
          "api::product-size-helper.product-size-helper",
          "api::product-stock.product-stock",
          "api::product-stock-log.product-stock-log",
          "api::product-tag.product-tag",
          "api::product-variation.product-variation",
          "api::product-variation-color.product-variation-color",
          "api::product-variation-model.product-variation-model",
          "api::product-variation-size.product-variation-size",
          "api::shipping.shipping",
          "api::shipping-city.shipping-city",
          "api::shipping-province.shipping-province",
        ],
      },
    },
  },
});
