import type { Metadata } from "next";
import { Provider } from "jotai";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "../styles/fonts.css";
import { NuqsAdapter } from "nuqs/adapters/next";
import { CartProvider } from "@/contexts/CartContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`font-peyda-fanum antialiased`}>
        <Provider>
          <CartProvider>
            <NuqsAdapter>{children}</NuqsAdapter>
          </CartProvider>
        </Provider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
