import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "../styles/fonts.css";
import "../styles/components.css";
import { NuqsAdapter } from "nuqs/adapters/next";
import { CartProvider } from "@/contexts/CartContext";
import Providers from "./Providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`font-peyda-fanum antialiased preload-blur`}>
        <CartProvider>
          <NuqsAdapter>
            <Providers>{children}</Providers>
          </NuqsAdapter>
        </CartProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
